# -*- coding: utf-8 -*-
"""IrisFlowerClassification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ew0UC2l5WVBk0WzfPIIvnXxtSZrU_sm1
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
iris= pd.read_csv("/content/IRIS.csv")

iris

iris.head()#first five rows of the dataset

iris.describe()#last five rows of the dataset

print("Target Labels",iris["species"].unique())  #target values

#scatter plot according to sepal length and sepal width
import plotly.express as px
fig=px.scatter(iris,x="sepal_width",y="sepal_length",color="species")
fig.show()

#KNN classification algorithm to train iris classification model

x= iris.drop("species",axis=1)
y= iris["species"]
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y,test_size=0.2, random_state=0)  #splitting data into training and test sets
from sklearn.neighbors import KNeighborsClassifier
knn= KNeighborsClassifier(n_neighbors=1)
knn.fit(x_train, y_train)

#input a set of measurements of iris flower and use the model to predict iris species
x_new = np.array([[5, 2.9, 1, 0.2]])
prediction = knn.predict(x_new)
print("Prediction: {}".format(prediction))

"""So this is how you can train a ML model for task of Iris Flower Classification using Python."""