# -*- coding: utf-8 -*-
"""SalesPrediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PoBiVRzWy2t3udQoiQAHG6-I5TnbIxT0
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

data=pd.read_csv("/content/advertising.xls")
data

data.head() #first five rows of the dataset

print(data.isnull().sum())

"""this means that the dataset does not contain any null values."""

#correlation between features
plt.style.use('seaborn-whitegrid')
plt.figure(figsize=(12,10))
sns.heatmap(data.corr())
plt.show()

#training model using Linear Regression

x= np.array(data.drop(["Sales"],axis=1)) #use axis=1 to indicate column wise operation
y= np.array(data["Sales"])

xtrain, xtest, ytrain, ytest= train_test_split(x, y, test_size=0.2, random_state=42)

model=LinearRegression()
model.fit(xtrain, ytrain)
ypred= model.predict(xtest)

data_predicted= pd.DataFrame(data={"Predicted Sales": ypred.flatten()})
data_predicted